- build.gradle
https://tools.hmcts.net/jira/browse/SIDM-1152
Changed GAV for the published artefact so that it aligns better with IdAM release versioning.
```
[ ] Yes
[x] No
```
> Changed the version for the idam-api-spec artefact published to bintray and jcenter

- build.gradle
- pom.xml
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1362
Added new `/authorizationCode` endpoint
```
[ ] Yes
[x] No
```
> SIDM-1362: Added authorizationCode endpoint

- build.gradle
- pom.xml
- src/main/resources/api.yaml
**Before creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/SIDM-1359
Added new type and property for test user creation endpoint Request Object.
```
[ ] Yes
[ ] No
```
> SIDM-1359 - added userGroup property in test user creation request.

- build.gradle
- pom.xml
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1375
Added new enpoint for testing support
```
[ ] Yes
[X ] No
```
> SIDM-1375 - Added new enpoint in testing support.

- build.gradle
- pom.xml
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1375
deleted property in User object.
```
[ ] Yes
[ ] No
```
> SIDM-1375 - deleted property in User object.

- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1403
Added activation redirect url
```
[ ] Yes
[ ] No
```
> Added activation redirect url

- build.gradle
- pom.xml
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1563
Add query filter to search for services by clientId
Related PR: https://github.com/hmcts/idam-api-spec/pull/14
```
[ ] Yes
[x] No
```
> SIDM-1563: Add query filter to search for services by clientId

- build.gradle
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1266
Added DELETE user endpoint
```
[ ] Yes
[x] No
```
> SIDM-1266 Added DELETE user endpoint

- build.gradle
- src/main/resources/api.yaml
Add testing support endpoint for adding/removing redirect URIs to/from a service.
```
[ ] Yes
[x] No
```
> Add testing support endpoint for adding/removing redirect URIs to/from a service

- build.gradle
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1971
Updated /oauth2/token endpoint
```
[ ] Yes
[x] No
```
> SIDM-1971 Implement OAuth2 client_credentials API

- build.gradle
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1972
Defined new endpoint for 3rd party users registration
```
[ ] Yes
[x] No
```
> SIDM-1972 Create new endpoint

- build.gradle
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1972
```
[ ] Yes
[x] No
```
> SIDM-1972 Corrected parameter name

- build.gradle
- src/main/resources/api.yaml
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1848
* New dynamic role assignment API definition
* Moved API definitions for v 1.1.2 into a separate YAML spec.
```
[ ] Yes
[x] No
```
> SIDM-1848: Swagger specification for the role assignment API

- build.gradle
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1847 (issue with empty strings)
Require at least a string of length one for first and last names
```
[ ] Yes
[x] No
```
> Specify minimum size for first and last names

- build.gradle
- src/main/resources/api.yaml
https://tools.hmcts.net/jira/browse/SIDM-1848
This allows for generating an access token with custom scope out of normal public user authentication or user uplift.
```
[ ] Yes
[x] No
```
> Allow for requesting additional scopes on user authentication

- build.gradle
- src/main/resources/api.yaml
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2224
Updated pattern for email validation to reject empty or invalid emails
```
[ ] Yes
[x] No
```
> SIDM-2224 Improved email validation

- build.gradle
- src/main/resources/api.yaml
- src/main/resources/public-editor-api.yaml
> SIDM-2224 Stricter email validation

- build.gradle
- src/main/resources/api.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> [PREVIEW] SIDM 1988 - Added new endpoint for deleting all test data

- build.gradle
- src/main/resources/api.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> SIDM-2208 added optional scopes list to OAuth2Agent definition

- build.gradle
- src/main/resources/api.yaml
Re-opening this as it seems I will need this change after all
> SIDM-2308 Optional state parameter in SelfRegistration

- build.gradle
- src/main/resources/api.yaml
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2202
Added user resource and paths for get users, edit user, delete user
```
[ ] Yes
[ x ] No
```
> SIDM-2202 Added new user endpoint to API spec, increased version number

- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2202
adding email pattern for regex validation in User object
```
[ ] Yes
[ x ] No
```
> SIDM-2022 adding email pattern to user object definition

- build.gradle
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2202
adding auth headers to api definition, renamed deleteUser operation, increased version
```
[ ] Yes
[ x ] No
```
>  adding auth headers to api definition, renamed deleteUser operation, increased version

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/resources/public-editor-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2202
added missing error codes from some operations
removed account status enum
made userId as non mandatory in User update request object
```
[ ] Yes
[ x ] No
```
> updates to API spec

- build.gradle
https://tools.hmcts.net/jira/browse/SIDM-2236
Fixed dependencies
```
[ ] Yes
[x] No
```
> SIDM-2236 

- build.gradle
- src/main/resources/external-user-mgmt-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2205
changes to spec to refine error codes, increased version
```
[ ] Yes
[ x ] No
```
> SIDM-2205 - changes to spec to refine error codes, increased version

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2443
Add prefix to deleteAllTestData endpoint to selectively delete services and roles.
```
[ ] Yes
[x] No
```
> SIDM-2443: Add prefix parameter to deleteAllTestData endpoint

- build.gradle
- src/main/resources/external-dynamic-role-assign-api.yaml
- src/main/resources/external-user-mgmt-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2592
Extracted Dynamic Role Assign API from User Mgmt API definition
```
[ ] Yes
[ x ] No
```
> [PREVIEW] SIDM-2592 - Extracted Dynamic Role Assign API from User Mgmt API definition

- build.gradle
- src/main/resources/external-user-mgmt-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2587
added /users endpoint with email query parameter
```
[ ] Yes
[ x ] No
```
> [PREVIEW] SIDM-2589 - added /users endpoint with email query parameter

- build.gradle
- src/main/resources/openid-connect.yaml
As we will be used as an official OIDC provider, we must completely comply with the
spec
```
[ ] Yes
[X] No
```
> SIDM-1427 Adding a more complete OIDC implementation

- build.gradle
- src/main/resources/openid-connect.yaml
Allows services to discover relevant details about the provider configuration
```
[ ] Yes
[X] No
```
> SIDM-2376 OIDC discovery well-known endpoint

- build.gradle
- src/main/resources/openid-connect.yaml
> SIDM-2662 add refresh_token to /token

- build.gradle
- src/main/resources/internal-admin-api.yaml
- src/main/resources/openid-connect.yaml
Switch web-publics mechanism for acquiring authorization/authentication to 
the same as everyone else 
```
[X] Yes
[ ] No
```
> SIDM-2661 Preparing to accomodate OIDC Sessions

- build.gradle
- src/main/resources/openid-connect.yaml
Pretty simple stuff
```
[ ] Yes
[X] No
```
> SIDM 2684 Adding an End Session endpoint to OIDC Controller

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/resources/external-user-mgmt-api.yaml
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-2682
Changing spec to add 'pending' account status and UUID to UserRegistrationRequest payload
```
[ ] Yes
[ x ] No
```
> SIDM-2682 Changing spec to add 'pending' account status and UUID to UserRegistrationRequest payload

- build.gradle
> SIDM-2682 - upgrading Gradle Bintray plugin

- build.gradle
- src/main/resources/external-user-mgmt-api.yaml
- src/main/resources/shared.yaml
An ElasticSearch driven search function for the User object
```
[ ] Yes
[X] No
```
> SIDM-2644 Adding the User management search query

- src/main/resources/external-user-mgmt-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2780
changed endpoint for role revoke 
```
[ ] Yes
[ x ] No
```
> [PREVIEW] changed endpoint for role delete

- build.gradle
https://tools.hmcts.net/jira/browse/SIDM-2780
forgot to include the new version
```
[ ] Yes
[ ] No
```
> increasing api version

- build.gradle
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-2717
added linkedRoles to Role model
```
[ ] Yes
[ x ] No
```
> SIDM-2717 - added linkedRoles to Role model

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2647
Scope creep from https://tools.hmcts.net/jira/browse/SIDM-2647
Shrav would benefit from having a test endpoint in order to test this ticket.
Question:
- this is the first api-spec PR, I'm not sure if I should be updating anything else as part of this ticket. In the gradle file or whatever? Such as git tags? Let me know.
```
[ ] Yes
[x] No
```
> sidm-2647-purge: add endpoint to test controller spec

- build.gradle
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-2530
Update class UpdateRole, add attribute linkedRoles
```
[ ] Yes
[x] No
```
> SIDM-2530-linked-webUpdateRole add support for linkedRoles

- build.gradle
- src/main/resources/internal-admin-api.yaml
Please ignore the file formatting white space changes
> [PREVIEW] SIDM-2637 Pact state change endpoint

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2954
Add refresh cache testing support endpoint
> add cache refresh

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3153
- add policies api yaml
```
[ ] Yes
[x] No
```
> SIDM-3153 add Policies Api spec

- build.gradle
https://tools.hmcts.net/jira/browse/SIDM-3135
- bump
```
[ ] Yes
[x] No
```
> SIDM-3153 bump version to 2.14.1

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3147
- policy api: add get/put/delete
```
[ ] Yes
[x] No
```
> SIDM-3147-pol-creat): v2.14.2 policy api with get/put/delete

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3147
- add proper policyApi post support
```
[ ] Yes
[x] No
```
> SIDM-3147: v2.14.3 with policy post support

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3147
- fr spec was wrong and ambiguous we had to re-spec some properties into maps
```
[ ] Yes
[x] No
```
> SIDM-3147 v2.14.4 fix forgerock policies spec :package:

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2856
Add clientId to the ActivationResult.
```
[ ] Yes
[x] No
```
> SIDM-2856 Add clientId to the ActivationResult.

- build.gradle
- src/main/resources/openid-connect.yaml
https://tools.hmcts.net/jira/browse/SIDM-3293
Update api spec to support otp chain
```
[ ] Yes
[x] No
```
> feat(SIDM-3293-otp-spec): v2.15.0 with OTP idam-api spec

- build.gradle
- src/main/resources/internal-admin-api.yaml
INCORRECT_OTP, INVALID_OTP_SESSION
https://tools.hmcts.net/jira/browse/SIDM-3294
add new error codes INCORRECT_OTP, INVALID_OTP_SESSION
```
[ ] Yes
[X] No
```
> feat(SIDM-3294-otp-fail): v2.15.1 new error codes

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3324
add endpoint GET /policies
based on https://github.com/hmcts/idam-forgerock-http-client/pull/12
```
[ ] Yes
[x] No
```
> feat(SIDM-3324-getall-pols): v2.16.0 add GET /policies

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3248
fix too many otp attempts
```
[ ] Yes
[x] No
```
> feat(SIDM-3248-val4): v2.17.0 OTP: add support for too many attempts

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-2040
- blacklisted: Your password is too easy to guess
- containing personal info: Do not include your name or email in your password
- did not match rules: Your password didn't have all the required characters
```
[ ] Yes
[x] No
```
before | after
--- | ---
> feat(SIDM-2040-pw): v2.17.1 update password reset messages

- build.gradle
- src/main/resources/external-policies-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3441
Remove auth header from /policies/evaluate as it's not required
```
[ ] Yes
[x] No
```
> feat(SIDM-3441-spec): /policies/evaluate: remove auth header

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3397
```
[ ] Yes
[x] No
```
> SIDM-3397 Add PasswordResetValidation.

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-3397
```
[x] Yes
[ ] No
```
> SIDM-3397 Rename ForgotPasswordRequest to ForgotPasswordDetails.

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-4211
Added error to enum for stale user register
```
[ ] Yes
[x ] No
```
> added error for stale user

- build.gradle
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-4194
Added field stale to user object
```
[ ] Yes
[ x] No
```
> added field stale

- build.gradle
- src/main/resources/internal-admin-api.yaml
- src/main/resources/openid-connect.yaml
- change how we authenticate users (mostly change required parameters)
```
[x] Yes - not backwards compatible
[ ] No
```
> SIDM-4092 WIP

- build.gradle
- src/main/resources/openid-connect.yaml
Set the version to 2.18.2. Re-introduce AuthTrees changes.
```
[x] Yes
[ ] No
```
> SIDM-4092 Set the version to 2.18.2. Re-introduce AuthTrees changes.

- build.gradle
- src/main/resources/internal-admin-api.yaml
[https://tools.hmcts.net/jira/browse/SIDM-4407](url)
Extending the service object with a list of external SSO Providers
> Adding ssoProviders to service object

- build.gradle
- src/main/resources/external-sso-api.yaml
- src/main/resources/shared.yaml
New and shiney
https://tools.hmcts.net/confluence/display/SISM/Federated+SSO+to+CFT+Services+for+the+Judiciary#FederatedSSOtoCFTServicesfortheJudiciary-3.3.4.APIWeb-App
I made on minor change where I left out the post body in /federatedusers
I feel the final solution will not require this information
> Introducing the SSO Provider API

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-4411
```
[ ] Yes
[ x] No
```
> SIDM-4411 

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-4832
```
[ ] Yes
[x ] No
```
> SIDM-4832: removed unused boolean

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-5884
Add INVALID_SESSION and ERROR to ErrorResponse since they're both valid authentication outcomes.
```
[ ] Yes
[X] No
```
> Sidm 5884 invalid session code

- build.gradle
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-6016
Mock refdata organisation mfa call
```
[ ] Yes
[X] No
```
> SIDM-6016 mock refdata organisation mfa call

- build.gradle
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-6914
Add account locked time property to User model
```
[ ] Yes
[x] No
```
> SIDM-6914 Add account locked time property to User model

- build.gradle
- src/main/resources/openid-connect.yaml
https://tools.hmcts.net/jira/browse/SIDM-7542
Add PKCE extension to OIDC authentication with authorization code
```
[ ] Yes
[x] No
```
> SIDM-7542 Add PKCE extension to OIDC authentication with authorization code

- build.gradle
- src/main/resources/shared.yaml
https://tools.hmcts.net/jira/browse/SIDM-7998
Validate for no spaces in user email
```
[ ] Yes
[X] No
```
> SIDM-7998 check for spaces in emails

- build.gradle
- src/main/resources/external-bulk-request-api.yaml
- src/main/resources/external-user-mgmt-api.yaml
- src/main/resources/internal-admin-api.yaml
https://tools.hmcts.net/jira/browse/SIDM-7998
Validate for no spaces in user email
```
[ ] Yes
[X] No
```
> SIDM-7998 check for spaces in emails (part 2)
